[project]
name = "einops-animation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.1",
    "ffmpeg>=1.4",
    "manim>=0.19.1",
]
